resolver: lts-8.13
packages:
- memento
- memento-simple-fltkhs
- monoidal-diff
- simple-fltkhs
- location:
    git: git@github.com:pbrisbin/doctest-discover.git
    commit: df327799f7d74bcfdcb791323c0bca5c2c398c54
extra-deps:
- fltkhs-0.5.4.2
- debug-0.0.2

allow-newer: true
