name: simple-fltkhs
version: 0.1.0.0
synopsis: |
  A very limited subset of fltkhs which only supports windows and buttons.
description: |
  Like most bindings to non-Haskell GUI libraries, fltkhs's API is very large.
  In order to demonstrate how wrapping such an API would work without being
  overburdened by details, this library exposes a small part of fltkhs via a
  much smaller, simpler API.
maintainer: Samuel Gélineau <gelisam@gmail.com>
license: PublicDomain
github: gelisam/memento
category: GUI

flags:
  FastCompile:
    description: Turn off optimizations for faster compilation
    manual: True
    default: False

ghc-options: -Wall -Werror
when:
  - condition: flag(FastCompile)
    then:
      ghc-options: -fno-specialise -fmax-simplifier-iterations=0 -fsimplifier-phases=0
    else:
      ghc-options: -O2
  - condition: os(windows)
    ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
  - condition: os(darwin)
    ghc-options: "-optl-Wl,-lfltkc"
  - condition: "!os(darwin) && !os(windows)"
    ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"

dependencies:
  - base
  - fltkhs
  - text
  - transformers

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: demo
  dependencies:
    - simple-fltkhs

tests:
  doctests:
    main: doctests.hs
    ghc-options: [-threaded]
    source-dirs:
      - test
      - src
      - demo
    dependencies:
      - doctest
      - doctest-discover
