name: memento-simple-fltkhs
version: 0.1.0.0
synopsis: |
  Wrapping a low-level GUI library using memento: a proof-of-concept.
description: |
  Libraries which provide bindings to an upstream non-Haskell GUI library all
  have an imperative API, because that's the API which the upstream library
  has. 'memento' makes it possible to implement a pure API on top of those
  low-level bindings. We demonstrate the technique by wrapping a very small GUI
  library, 'simple-fltkhs'.
maintainer: Samuel Gélineau <gelisam@gmail.com>
license: PublicDomain
github: gelisam/memento
category: GUI

flags:
  FastCompile:
    description: Turn off optimizations for faster compilation
    manual: True
    default: False

ghc-options: -Wall -Werror
when:
  - condition: flag(FastCompile)
    then:
      ghc-options: -fno-specialise -fmax-simplifier-iterations=0 -fsimplifier-phases=0
    else:
      ghc-options: -O2
  - condition: os(windows)
    ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
  - condition: os(darwin)
    ghc-options: "-optl-Wl,-lfltkc"
  - condition: "!os(darwin) && !os(windows)"
    ghc-options: -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"

dependencies:
  - base
  - fltkhs
  - memento
  - monoidal-diff
  - simple-fltkhs

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: demo
  dependencies:
    - memento-simple-fltkhs

tests:
  doctests:
    main: doctests.hs
    ghc-options: [-threaded]
    source-dirs:
      - test
      - src
      - demo
    dependencies:
      - doctest
      - doctest-discover
